### PR TITLE
Investigate drawing problems

### PR DESCRIPTION
**Pull request by lestrrat**

### CODE REVIEW

**Comment by lestrrat** [comment]
@zchee Well, this so far has fixed one problem that *I* was seeing (but may not necessarily be the one you were seeing on #313). Please check it out if you have some time

**Comment by zchee** [comment]
@lestrrat Thanks! I tested.
Not tested yet all because the freeze problem(goroutine deadlock?) occasionally occurs, but may be solved!
I will continue to use (this version)peco, and observe.

BTW, I did not say but peco also have the slow filtering problem.
Take a screencast was late because zsh history is sensitive data, but finished now. I will post to new issue thread.
If you have time, please confirm it.

**Comment by zchee** [comment]
@lestrrat I was create a new isuue thread and upload screencast.
https://github.com/peco/peco/issues/320
Please see it if you have time.

**Comment by lestrrat** [comment]
Okay, so according to #320, the deadlock is gone, so merging this and closing.

**Pull request merged**
