### PR TITLE
fix default layout

### LINKED ISSUE #283: rcfile's layout config not works
Hi

I tried to `--layout=bottom-up` option from rcfile like this:

```
{
  "Layout": "bottom-up"
}
```

but layout still top-down. `peco --layout=bottom-up` is works.

Is this a bug? or my config are mistaken?

Thanks

### PR DESCRIPTION
**Pull request by mattn**
Close #283

### CODE REVIEW

**Comment by syohex** [comment]
We need to update or remove test about default layout which is returned from `NewCtx`.

https://github.com/peco/peco/blob/97728cbc21ffbebe55fcda085525a1570f1fed69/issues_test.go#L72

**Comment by mattn** [comment]
Thank you

**Comment by syohex** [comment]
Looks good.

**Comment by syohex** [comment]
Ping @lestrrat. Can we merge this ?

**Comment by mattn** [comment]
fixed

**Pull request merged**
