### PR TITLE
Limit ScrollRight until the right end of buffer

### PR DESCRIPTION
**Pull request by k0kubun**
Related to https://github.com/peco/peco/pull/249

I don't want peco to unlimitedly scroll to right by peco.ScrollRight. I implemented the scroll limit to right direction.

## before
before

## after
after

### CODE REVIEW

**Comment by lestrrat** [comment]
Just a thought: What happens when you have a ridiculous number of lines?

**Comment by k0kubun** [comment]
I couldn't guess what you worry about. At least for my `fc -l -r -n 1 | peco`, which is the largest input in my use cases, it works as I expected for this implementation.

I agree that ideally we should limit it to the right end of lines visible on the current page. I implemented like this because I don't know peco's internals well and this behavior is simple that I can easily think of it.

**Comment by lestrrat** [comment]
No, you're talking about the *width*, I'm talking about the *number of lines*.
I only glanced, so am not sure, but are you calculating `Column` by going through all the lines in the buffer? What happens if you have 5 million lines?

**Comment by k0kubun** [comment]
> I only glanced, so am not sure, but are you calculating Column by going through all the lines in the buffer? What happens if you have 5 million lines?

Maybe you're worrying about performance regression by that calculation? `fc -l -r -n 1 | peco` was the largest *lines* in my use cases and it was not bad. But it'd be better to test some input with more lines.

I think to "limit it to the right end of lines visible on the current page" can also solve that problem because calculation will be done for only visible lines. I'll consider such implementation.

**Comment by lestrrat** [comment]
Yeah, that's what I meant.

> I think to "limit it to the right end of lines visible on the current page" can also solve that problem because calculation will be done for only visible lines. I'll consider such implementation.

Yes! I'd love to see that.

**Comment by lestrrat** [comment]
@k0kubun there was a bug fix I needed to do for `--exec`, and I'd like to release soon. So I took this PR and rewrote it in terms of `FilteredBuffer`, which only contain those lines required to draw the screen and thus save a tree or two.

Please see if #412 works for you.

**Pull request closed without merging**
