### PR TITLE
Implement hit-a-hint

### PR DESCRIPTION
**Pull request by lestrrat**
Second take of #261

- "@" toggles "SingleKeyJump" mode
- list of hot keys are displayed to the left
- selecting the key allows you to jump to the line, and
  peco exits by selecting that line

### CODE REVIEW

**Comment by syohex** [comment]
Hint characters does not appeared if query is not empty.

1. type `@`. Hint characters appears. OK
2. Disable Hint by `@`
3. Input `Mem` as query
4. type `@`. Hint characters not appears. not OK
5. But I can select candidates by hint character(In this case, I typed `d` for 3rd candidate)

output

**Comment by mattn** [comment]
nothing appeared.

**Comment by lestrrat** [comment]
I grok @syohex 's symptoms, but I don't understand what's going on with @mattn ...

**Comment by lestrrat** [comment]
problems observed by @syohex should now be fixed with d07dfc9.
I have not clue what @mattn is seeing atm...

**Comment by mattn** [comment]
Should be
```diff
diff --git a/ctx.go b/ctx.go
index 3ba8480..6813675 100644
--- a/ctx.go
+++ b/ctx.go
@@ -110,6 +110,16 @@ func newCtx(o CtxOptions, hubBufferSize int) *Ctx {
 	c.filters.Add(NewSmartCaseFilter())
 	c.filters.Add(NewRegexpFilter())
 
+	c.config.SingleKeyJumpMap = make(map[rune]uint)
+	chrs := "asdfghjklzxcvbnmqwertyuiop"
+	for i := 0; i < len(chrs); i++ {
+		c.config.SingleKeyJumpMap[rune(chrs[i])] = uint(i)
+	}
+	c.config.SingleKeyJumpList = make([]rune, len(c.config.SingleKeyJumpMap))
+	for k, v := range c.config.SingleKeyJumpMap {
+		c.config.SingleKeyJumpList[v] = k
+	}
+
 	return c
 }
 
@@ -132,18 +142,6 @@ func (c *Ctx) ReadConfig(file string) error {
 		}
 	}
 
-	if len(c.config.SingleKeyJumpMap) == 0 {
-		c.config.SingleKeyJumpMap = make(map[rune]uint)
-		chrs := "asdfghjklzxcvbnmqwertyuiop"
-		for i := 0; i < len(chrs); i++ {
-			c.config.SingleKeyJumpMap[rune(chrs[i])] = uint(i)
-		}
-	}
-	c.config.SingleKeyJumpList = make([]rune, len(c.config.SingleKeyJumpMap))
-	for k, v := range c.config.SingleKeyJumpMap {
-		c.config.SingleKeyJumpList[v] = k
-	}
-
 	return nil
 }
 
```

**Comment by mattn** [comment]
previous change is not good.
When rcfile not exists, ReadConfig isn't called. So the initialization of SingleKeyJumpList should be done at newCtx.

**Comment by lestrrat** [comment]
Ah righto.

**Comment by syohex** [comment]
I confirmed my reported issue was fixed.

BTW: Should peco assign this command to `@` by default ? We cannot narrow candidates by `@` character, e.g. E-mail addresses.(I suppose such case is a rare case and we can also change key bindings by configuration file.)

**Comment by lestrrat** [comment]
@syohex very true. let's create some config option to enable this

**Comment by rubikitch** [comment]
Thank you for great work!!

http://rubikitch.com/f/anything-hit-a-hint.ogv

This movie (1.3MB) shows that I selected *scratch* by hitting "@d".
Showing hints initially is more comfortable, I think.
I'll learn to convert ogv into gif.

**Comment by lestrrat** [comment]
Actually, all we need to do was to not register the action by default. The user can just enable it by

```
{
  "Keymap": {
    "@": "peco.ToggleSingleKeyJump"
  }
}
```

Will implement it

**Comment by mattn** [comment]
@lestrrat no key-assign?

**Comment by lestrrat** [comment]
@mattn I made it so that there's no key assigned by default

**Comment by mattn** [comment]
@lestrrat agreed

**Comment by syohex** [comment]
Looks good!!! :+1:

**Comment by lestrrat** [comment]
Hopefully as of the latest commit, and using this config should fulfill @rubikitch 's requests

```
{
  "SingleKeyJump": {
    "ShowPrefix": true
  },
  "Keymap": {
    "@": "peco.ToggleSingleKeyJump"
  }
}
```

**Comment by mattn** [comment]
BTW, if there are lines over 26 letters, what happen? will be crash? or dancing?

**Comment by lestrrat** [comment]
@mattn it will just not show up. sorry, no dancing.

image

**Comment by lestrrat** [comment]
@rubikitch please give us one final review. once done, I'll merge and release 0.3.4

**Comment by rubikitch** [comment]
Works perfect!! Thank you very much!!! I love SingleKeyJump.ShowPrefix == true

**Pull request merged**
