### PR TITLE
Add darwin-arm64

### LINKED ISSUE #519: Request: binary release for arm64 macOS
# What is the peco version, OS, architecture? 

N/A

# Abstract

It's nice that a binary for arm64 macOS is available in https://github.com/peco/peco/releases

# Discussion

I usually get peco from https://github.com/peco/peco/releases.
So I hope a binary for arm64 macOS is available in release page.

### PR DESCRIPTION
**Pull request by skaji**
Fix #519

### CODE REVIEW

**Comment by syohex** [comment]
It seems older go(1.13) of CI does not support arch64 and darwin build.

**Comment by skaji** [comment]
@syohex Thanks for your review.

I add a version check by perl (sorry, I was not able to write a version check by shell script);
build/release darwin-arm64 is disabled on go1.15 or lower.

travis ci still fails, but the failure seems to be not related to this PR:
```
panic: send on closed channel
goroutine 349 [running]:
github.com/peco/peco.(*Peco).selectOneAndExitIfPossible(0xc008e8a380)
	/home/travis/gopath/src/github.com/peco/peco/peco.go:308 +0x160
github.com/peco/peco.(*Peco).Run.func5(0xc008e8a380)
	/home/travis/gopath/src/github.com/peco/peco/peco.go:392 +0x44
created by github.com/peco/peco.(*Peco).Run
	/home/travis/gopath/src/github.com/peco/peco/peco.go:386 +0x390
FAIL	github.com/peco/peco	20.468s
?   	github.com/peco/peco/cmd/peco	[no test files]
```

**Comment by lestrrat** [comment]
Let's just support the latest Go (1.16 for now)

**Comment by lestrrat** [comment]
And... we should probably move off of travis. Maybe in a separate PR

**Comment by skaji** [comment]
@lestrrat Thanks for your review.

I did force-push and now go1.16.x is used in travis ci 19f296d.

**Review by syohex — APPROVED** [review]
looks good

**Comment by lestrrat** [comment]
I'll go ahead and merge, but ATM I'm not sure when there will be a new release.
I've been meaning to, but haven't been able to convert this project to github.com/gdamore/tcell base

**Comment by lestrrat** [comment]
Anyways, thank you for your PR!

**Pull request merged**
