### PR TITLE
Add AUR installation instruction

### PR DESCRIPTION
**Pull request by pniedzwiedzinski**
I added installation instruction for Arch Linux

### CODE REVIEW

**Comment by syohex** [comment]
I don't know Arch linux well. It looks there are some AUR helpers other than `yay`, is it enough to list only `yay`, is it de fact standard ?

**Comment by pniedzwiedzinski** [comment]
I think `yay` is the most common, but if somebody uses something different it will still work - in most cases you will just need to replace `yay` with the one of your choice.

**Comment by imbsky** [comment]
@syohex No, this should not be approved yet. ToC will also need to be updated.

**Comment by lestrrat** [comment]
Completely missed this PR. ToC can be updated when somebody feels like it, so I'll just merge this for now

**Comment by imbsky** [comment]
@lestrrat I just opened a PR about ToC.

**Pull request merged**
