### PR TITLE
Tweak draw timing, and buffer

### PR DESCRIPTION
**Pull request by lestrrat**
Also fixes http://twitter.com/_zchee_/status/745210785740165120

### CODE REVIEW

**Comment by zchee** [comment]
@lestrrat Hi,
This fix resolved an issue that ***always*** freeze, Thanks!
But... now still occasionally freeze :(

In the same way, read the zsh history of about 4MB. And If I type the `LIC` to look for `cat LICENSE`, occasionally freeze.
It does not freeze when slowly typing(about 1 key per 1 sec), So I think related to the rate of key-typing also read of the `query`.
FYI, This issue did not occur before merging.

If hard to understand of explanation, I can upload a screencast and can create a new issue thread.
Thanks.

**Comment by lestrrat** [comment]
@zchee Yep, please file a new issue

**Comment by zchee** [comment]
@lestrrat OK, will do.

**Comment by lestrrat** [comment]
Also, if you are extremely good ad eye-grepping, you could do this:

```
go build -tags debug0 cmd/peco/peco.go
./peco [yourfile] >& out
```
This will spew out a BIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIG log of what peco is doing :)

**Comment by zchee** [comment]
@lestrrat 
> This will spew out a BIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIG log of what peco is doing :)

LOL, got it!
I will try it.

**Comment by zchee** [comment]
@lestrrat Sorry,
Just in case, post a quick debug log before create new issue thread.
(Sorry, `lise` is typo, correct is `lice` but result would be the same.)
```sh
.
.
.
|DEBUG|                     END OutputChannel.Send *peco.MatchedLine (2.085µs)
|DEBUG|                     START OutputChannel.Send *peco.MatchedLine
|DEBUG|                       Source: context.Done detected
|DEBUG|                       MemoryBuffer received context done
|DEBUG|                       New query 'lis'
|DEBUG|                     END MemoryBuffer.Accept (181.150012ms)
|DEBUG|                     START OutputChannel.Send struct { errors.cause; errors.location }
|DEBUG|                   END BasicLayout.Calculate 40 (178.555225ms)
|DEBUG|                     START UserPrompt.Draw
|DEBUG|                     |DEBUG|                   START Peco.SetCurrentLineBuffer *peco.MemoryBuffer
Filter.Work: finished running query
|DEBUG|                       END Peco.SetCurrentLineBuffer *peco.MemoryBuffer (2.894µs)
|DEBUG|                       waiting for query to finish
|DEBUG|                       START Source.Start
|DEBUG|                       START RegexpFilter.Accept
|DEBUG|                       START MemoryBuffer.Accept
|DEBUG|                           END UserPrompt.Draw (1.643005ms)
|DEBUG|                           START ListArea.Draw pp = 40, q = false
|DEBUG|                             START OutputChannel.Send *peco.MatchedLine
|DEBUG|                             END OutputChannel.Send *peco.MatchedLine (4.867µs)
.
.
.
|DEBUG|                             END OutputChannel.Send *peco.MatchedLine (2.358µs)
|DEBUG|                             START OutputChannel.Send *peco.MatchedLine
|DEBUG|                             END OutputChannel.Send *peco.MatchedLine (3.47µs)
|DEBUG|                             START OutputChannel.Send *peco.MatchedLine
|DEBUG|                             END OutputChannel.Send *peco.MatchedLine (2.305µs)
|DEBUG|                             START OutputChannel.Send *peco.MatchedLine
|DEBUG|                             END OutputChannel.Send *peco.MatchedLine (2.721µs)
|DEBUG|                             START OutputChannel.Send *peco.MatchedLine
|DEBUG|                             END OutputChannel.Send *peco.MatchedLine (2.714µs)
|DEBUG|                             START OutputChannel.Send *peco.MatchedLine
|DEBUG|                             END OutputChannel.Send *peco.MatchedLine (6.373µs)
|DEBUG|                             START OutputChannel.Send *peco.MatchedLine
|DEBUG|                               New query 'lise'
|DEBUG|                               Source: context.Done detected
|DEBUG|                             END OutputChannel.Send *peco.MatchedLine (37.429µs)
|DEBUG|                               START Peco.SetCurrentLineBuffer *peco.MemoryBuffer
|DEBUG|                               START OutputChannel.Send struct { errors.cause; errors.location }
|DEBUG|                               MemoryBuffer received context done
|DEBUG|                               START OutputChannel.Send *peco.MatchedLine
|DEBUG|                               END MemoryBuffer.Accept (84.332167ms)
|DEBUG|                                 ListArea.Draw: buffer size is 40, our view area is 40
# freeze point -->
# --- before pkill peco ---
|DEBUG|                                 Peco.Run cancel called
|DEBUG|                                 Peco.Run cancel called
|DEBUG|                                 Peco.Run cancel called
|DEBUG|                                 Peco.Run cancel called
|DEBUG|                               END Peco.Run (1m15.91438064s): ERROR: received signal: terminated
Error: received signal: terminated
# --- after pkill peco ---
```

I don't know peco normal behavior; This is the impression of just looking at the log.
But maybe correct behavior is,
```
START OutputChannel.Send *peco.MatchedLine
  Source: context.Done detected
 MemoryBuffer received context done
  New query 'lis'
  END MemoryBuffer.Accept (181.150012ms)
```
wrong behavior,
```
START OutputChannel.Send *peco.MatchedLine
  New query 'lise'
  Source: context.Done detected
END OutputChannel.Send *peco.MatchedLine (37.429µs)
  START Peco.SetCurrentLineBuffer *peco.MemoryBuffer
  START OutputChannel.Send struct { errors.cause; errors.location }
  MemoryBuffer received context done
```

peco use `"golang.org/x/net/context".Context.Done`?
And it must be `Done` the previous query, but sometimes the `Done` current query?
Hmm...

**Comment by lestrrat** [comment]
thanks for the log. This will have to put in my backburner for a while, but I will check when I get some tuits.

**Pull request merged**
