### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by coodix**
So cool filter was implemented but not described in readme. Just added few words about it.

### CODE REVIEW

**Comment by Sixeight** [comment]
Does fuzzy filter means #244 ?
This PR had closed by author, didn't merge.

**Comment by coodix** [comment]
Yes

**Comment by lestrrat** [comment]
Oh, did I mess it up?

**Comment by lestrrat** [comment]
I messed it up. reverting.

**Comment by coodix** [comment]
My mistake. Sorry.

**Comment by Sixeight** [comment]
:+1:

**Pull request merged**
