### PR TITLE
Fix typo in Changes

### PR DESCRIPTION
**Pull request by k0kubun**
Is it intentional?

### CODE REVIEW

**Comment by syohex** [comment]
Additionally
- https://github.com/peco/peco/blob/5b1bc48a30beff97d94c839dee5ee473e179ee1a/Changes#L15
  - environment variable name `PECO_MACHED_LINE_COUNT ` is wrong. `PECO_MATCHED_LINE_COUNT`.
- https://github.com/peco/peco/blob/5b1bc48a30beff97d94c839dee5ee473e179ee1a/Changes#L17
  - typo **Makefile**

**Comment by k0kubun** [comment]
Thanks. Added fixes and amended.

**Comment by syohex** [comment]
Thanks

**Comment by lestrrat** [comment]
Ah bah. 
that's what you get for doing stuff in haste.
thanks

**Pull request merged**
